### ISSUE TITLE
Channel value error when applying the checkpoint model to a custom point cloud

### ISSUE THREAD

**Issue by Redsparkfish** [csiro-robotics/LoGG3D-Net#7]
I have got some CAD model point clouds. But when I applied the model to them, in some cases it succeeded but in some other cases it would report a channel value error.

Here is the code segment:

save_path = os.path.join(os.path.dirname(__file__), 'checkpoints')
save_path = str(save_path) + cfg.checkpoint_name
checkpoint = torch.load(save_path)
model = get_pipeline(cfg.eval_pipeline)
model.load_state_dict(checkpoint['model_state_dict'])

base_file = data_dir + '/' + sorted(os.listdir(data_dir))[1]
base_pcd = np.load(base_file)
base_pcd = np.hstack((base_pcd, np.zeros(base_pcd.shape[0]).reshape(-1, 1))).astype(np.float32)  # My pcds do not have intensity.
current_input = make_sparse_tensor(base_pcd, cfg.voxel_size).cuda()
output_desc, output_feats = model(current_input)

And here is the error report:

Traceback (most recent call last):
  File "/media/uds/extra_space/LoGG3D-Net/Calc_Logg3D_Descs.py", line 50, in <module>
    output_desc, output_feats = model(current_input)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/models/pipelines/LOGG3D.py", line 25, in forward
    x = self.spvcnn(x)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/models/backbones/spvnas/core/models/semantic_kitti/spvcnn.py", line 197, in forward
    x4 = self.stage4(x3)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/models/backbones/spvnas/core/models/semantic_kitti/spvcnn.py", line 27, in forward
    out = self.net(x)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torchsparse/nn/modules/norm.py", line 13, in forward
    return fapply(input, super().forward)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torchsparse/nn/utils/apply.py", line 12, in fapply
    feats = fn(input.feats, *args, **kwargs)
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2448, in batch_norm
    _verify_batch_size(input.size())
  File "/media/uds/extra_space/LoGG3D-Net/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 81])

**Comment by kavisha725** [comment]
Could you print the shape of `base_pcd` and `current_input` for the cases that do and don't work. 

Also, please add the following to your code. 
```
model = model.cuda()
model.eval()
```

**Comment by Redsparkfish** [comment]
Oh, it was my ignorance to have skipped these 2 lines. Now everything works, thank you.
